# Generated by Django 3.1.3 on 2021-07-03 20:59

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210703_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True),
        ),
    ]
